name: Tyler's Mystery Shopper Package
url: https://mufflyt.github.io/tyler/mysteryshopper
description: >
  Tyler's Mystery Shopper package is designed to analyze appointment wait times using Poisson regression, while exploring the effects of insurance types on access to care.
template:
  bootstrap: 5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-pkgdown:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c('remotes', 'maps'))
          remotes::install_deps(dependencies = TRUE)

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.Rproj') }}-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ hashFiles('**/*.Rproj') }}
            ${{ runner.os }}-r-

      - name: Check pkgdown
        run: |
          Rscript -e 'pkgdown::check_pkgdown()'

      - name: Build pkgdown site
        run: |
          Rscript -e 'pkgdown::build_site()'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs

authors:
  - name: Tyler Muffly
    url: https://github.com/mufflyt
    roles: ["author", "creator"]
    orcid: 0000-0002-2044-1693

search:
  provider: lunr

sitemap: true
