# Declare all undeclared global variables
utils::globalVariables(c(
  "full_name", "address", "state_code", "npi",
  "total", "median_income", "state", "income_quartile", "Group", "summary_sentence",
  "zipcode", "zip_code", "insurance", "reason_for_exclusions",
  "business_days_until_appointment", "phone", "response_var", "var_interest",
  "int_var", "pred", "mean_pred", "Coefficient", "Variable", "Lower_CI", "Upper_CI",
  "phone_number", "data", "random_effect", "P_Value", "IRR", "CI_Lower", "CI_Upper",
  "queried_first_name", "queried_last_name", "state_code", "specialty_primary", "city",
  "case_assigned", "cases_repeated", "count_generalist", "count_specialist",
  "generalist_check", "specialist_check", "missing_generalists", "missing_specialists",
  "num_generalists", "num_specialists1", "first_name", "name", "last_name_searched",
  "first_name_searched", "Sentence_Part", ".", "grid_id", "ACOG_District",
  "physician_count", "postmastr.name.x", "postal", "state.abb", "state.name",
  "median_wait_time", "wait_time_q1", "wait_time_q3", "log_msg", "Driving Time (minutes)",
  "Year", "Division", "taxonomies_desc", "log_progress", "validate_input_data",
  "safely_convert_column_types", "handle_npi_numbers", "replicate_rows_with_labels",
  "add_unique_identifiers", "detect_academic_practice", "phone_number_cleanup",
  "add_timezone_column", "unite_columns_for_redcap", "save_cleaned_data",
  "load_and_validate_input_data", "validate_split_column", "assign_priority_rank",
  "assign_lab_assistants", "avoid_consecutive_physicians", "npi", "physician_count",
  "total_available", "long", "lat", "group", "region", utils::globalVariables(c(
    ".", ":=", "ACOG_District", "CI_Lower", "CI_Upper", "Coefficient", "Division",
    "Driving Time (minutes)", "Group", "ID", "IRR", "Lower_CI", "P_Value", "Sentence_Part",
    "State", "Upper_CI", "Variable", "Year", "address", "addresses_address_purpose",
    "addresses_state", "assign_income_quartiles", "assign_lab_assistants", "assign_priority_rank",
    "avoid_consecutive_physicians", "basic_credential", "basic_status",
    "business_days_until_appointment", "busy_signal", "calculate_grouped_estimates",
    "calculate_overall_estimate", "calculate_state_centroids", "case_assigned",
    "cases_repeated", "city", "clinician_data", "combine_statistics", "convert_state_names",
    "count_generalist", "count_physicians_per_state", "count_specialist", "detect_academic_practice",
    "first_name", "first_name_searched", "full_name", "generalist_check", "generate_and_save_map",
    "get_income_data", "grid_id", "group", "handle_npi_numbers", "hrrcity", "identifiers_desc",
    "income_quartile", "insurance", "int_var", "last_name_searched", "lat", "load_physician_data",
    "log_function_start", "log_msg", "log_progress", "long", "long_hold", "mean_pred",
    "median_household_income", "median_income", "median_wait_time", "merge_state_counts_with_map",
    "merge_subdivision_counts_with_map", "missing_generalists", "missing_specialists",
    "name", "not_accepting_new_patients", "npi", "nppes_collect_and_clean_data",
    "nppes_connect_to_duckdb", "nppes_create_table_from_csv", "nppes_disconnect_from_duckdb",
    "nppes_get_chunk", "nppes_get_total_row_count", "nppes_initialize_environment",
    "nppes_process_npi_table_chunk", "nppes_query_sample_data", "nppes_save_data_to_csv",
    "num_generalists", "num_specialists1", "phone", "phone_number", "phone_number_cleanup",
    "physician_count", "poisson", "postal", "postmastr.name.x", "pred", "queried_first_name",
    "queried_last_name", "random_effect", "reason_for_exclusions", "referral_required", "region",
    "replicate_rows_with_labels", "response_var", "safely_convert_column_types", "save_cleaned_data",
    "sd", "setNames", "specialist_check", "specialty_primary", "state", "state.abb", "state.name",
    "state_code", "str", "subdivision", "summary_sentence", "tableby.control", "taxonomies_desc",
    "temp_id", "total", "total_available", "total_exclusions", "unite_columns_for_redcap",
    "validate_input_data", "validate_split_column", "var_interest", "voicemail", "wait_time_q1",
    "wait_time_q3", "zip_code", "zipcode"))
))
